# Versione Docker compose file
version: '3'
services: 
    mongo:
        image: mongo
        restart: always
        volumes:
            - waf-db:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: test
    
    waf-frontend:
        image: waf-frontend
        build:
            context: .\frontend\
        restart: always

    waf-backend:
        image: waf-backend
        build:
            context: .\backend\
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - waf-backend-data:/vol
        networks:
            default:
            waf-network:
                ipv4_address: 172.20.0.10
        environment:
            PROXY: 1
            PROXY_SSL: "on"
            PROXY_PRESERVE_HOST: "off"
            PARANOIA: 1
            MODSEC_AUDIT_LOG: /vol/audit.log
            ALLOWED_METHODS: "GET HEAD POST OPTIONS DELETE PUT PATCH"
volumes:
    waf-db:
    waf-backend-data:
networks:
    default:
        ipam:
            config:
                - subnet: "172.16.0.0/16"
                  gateway: "172.16.0.1"
    waf-network:
        name: "waf-network"
        ipam:
            config:
                - subnet: "172.20.0.0/16"
                  gateway: "172.20.0.1"