# Versione Docker compose file
version: '3'
services: 
    mongo:
        image: mongo
        restart: always
        volumes:
            - waf-db:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: test

    mongo-express:
        image: mongo-express
        restart: always
        ports:
        - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: test
            ME_CONFIG_MONGODB_URL: mongodb://root:test@mongo:27017/
    
    waf-frontend:
        image: httpd
        restart: always
        volumes:
            - /home/alex/Scrivania/waf-app/frontend/waf-frontend/dist/waf-frontend:/waf-frontend
            - /home/alex/Scrivania/waf-app/frontend/waf-frontend-httpd.conf:/usr/local/apache2/conf/httpd.conf
            - /home/alex/Scrivania/waf-app/frontend/waf-frontend-httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf

    waf-backend:
        build:
            context: ./backend/
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - /home/alex/Scrivania/waf-app/backend/vol:/vol
            - /home/alex/Scrivania/waf-app/backend/waf-httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
            - /home/alex/Scrivania/waf-app/backend/waf-httpd-custom.conf:/usr/local/apache2/conf/extra/waf-custom.conf
        networks:
            - default
            - waf-network
        environment:
            PROXY: 1
            PROXY_SSL: "on"
            PROXY_PRESERVE_HOST: "off"
            PARANOIA: 1
            MODSEC_AUDIT_LOG: /vol/audit.log
            ALLOWED_METHODS: "GET HEAD POST OPTIONS DELETE PUT PATCH"
volumes:
    waf-db:
networks:
    default:
    waf-network:
        name: "waf-network"